version: '3'
services:
  python:
    build:
      context: .
      dockerfile: ./Dockerfile
    container_name: python_test_trade_marketing
    restart: unless-stopped
    logging: # https://docs.docker.com/compose/compose-file/#loggin
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "10"
    tty: true
    ports:
      - "0.0.0.0:1010:80"
    volumes:
      - .:/code


#Volumes
volumes:
  dbdata:
    driver: local
